### ISSUE TITLE
[NEW] Editing Restaurant Name in -edit_order doesn't update Customer's order list.

### ISSUE THREAD

**Issue by MackyMaguire** [AY1920S1-CS2103T-T12-2/main#224]
The new order is displayed in the UI (and can be completed) but I don't think it is updated in the database itself. Because when I try to delete it, the app throws `java.lang.reflect.InvocationTargetException`

And when I remove the line `model.deleteOrderInCustomer(orderToDelete);` in `deleteOrderCommand` no error is thrown. So I guess the error came from there.

**Comment by ryantay232** [comment]
Fixed
